import sys; sys.path.insert(0, ".")
import os
import json
from easyrl.core.config import load_config

def generate_code(config, output_dir):
    print("Generating code in directory: {}".format(output_dir))
    os.makedirs(output_dir, exist_ok=True)

    # __init__.py
    init_path = os.path.join(output_dir, "__init__.py")
    with open(init_path, "w") as f:
        f.write('"""\nRL Experiment Package\n\nAuto-generated by EasyRL CLI.\n"""')
    print("Created: {}".format(init_path))

    # config.py
    config_path = os.path.join(output_dir, "config.py")
    with open(config_path, "w") as f:
        f.write("# config.py\n# Auto-generated configuration for RL experiment\n\nconfig = {}\n".format(json.dumps(config, indent=4)))
    print("Created: {}".format(config_path))

    # main.py
    main_content = '''
from easyrl import RLAgent, Environment
from .config import config

def main():
    # Load environment
    env = Environment(config["env_config"])
    
    # Initialize agent
    agent = RLAgent(config)
    
    # Train the agent
    print("Training agent...")
    train_metrics = agent.train(env, steps=10000)
    print("Training metrics:", train_metrics)
    
    # Evaluate the agent
    print("Evaluating agent...")
    eval_metrics = agent.evaluate(env, episodes=10)
    print("Evaluation metrics:", eval_metrics)

if __name__ == "__main__":
    main()
'''
    main_path = os.path.join(output_dir, "main.py")
    with open(main_path, "w") as f:
        f.write(main_content)
    print("Created: {}".format(main_path))

    # run.py
    run_content = '''
from main import main

if __name__ == "__main__":
    main()
'''
    run_path = os.path.join(output_dir, "run.py")
    with open(run_path, "w") as f:
        f.write(run_content)
    print("Created: {}".format(run_path))

    print("Code generation complete! You can now run 'python run.py' in the directory.")

config = load_config("sample_config.json")
print("Config loaded:", config)
generate_code(config, "test_dir")